Migration 8
ipfs/js-ipfs-repo-migrations pull request #4
Opened 2019-10-22 10:31 UTC by AuHau

2019-11-11 12:31 UTC, alanshaw requested changes
Do you think that we should move `migrations` to `src/migrations`?

Can you explain for me the need for `keys-encoding.js`?

2019-11-11 12:31 UTC, alanshaw commented on migrations/migration-8/blocks-to-multihash.js
> +    const batch = store.batch()
We can't buffer the entire contents of a repo into memory. This has to be done incrementally.

2019-11-14 10:41 UTC, AuHau commented
Tbh I like having the `migrations` separate from `src`. The `src` contains the migration's framework which the `migrations` does not directly belong to.

Regarding the `key-encoding` this is related to https://github.com/ipfs/js-ipfs/issues/1937 but as mentioned in related PR https://github.com/ipfs/js-ipfs/pull/2410 I am not sure if it is needed (please see the PR and comment there if possible)

2020-06-03 14:34 UTC, achingbrain commented
Tests are failing in the browser due to https://github.com/ipfs/js-datastore-idb/issues/6

2020-06-09 18:14 UTC, achingbrain commented
Depends on:

- [ ] https://github.com/ipfs/js-datastore-idb/pull/7

2020-06-25 11:47 UTC, merged